version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13.4
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-114-242.compute-1.amazonaws.com
            port: '5432'
            database: d8p8bm22d5b7e2
            ssl: true
            user: ippvxwtvtizzxz
            password: 71783ff5f8306c6acae512d2da7dc4782166e5ebe4102708f1b38e67bc16c3ca
            migrations: true
